#!/bin/bash
#SBATCH -J myMPI           # job name
#SBATCH -o "/work/05184/xuduo117/project_CNN/NeuralSpaceBubbles/batch_out/out_file_%J.out"       # output and error file name (%j expands to jobID)
#SBATCH -N 1               # Total # of nodes 
#SBATCH -n 4              # total number of mpi tasks requested
#SBATCH -p gtx     # queue (partition) -- normal, development, etc.
#SBATCH -t 24:00:00        # run time (hh:mm:ss) - 1.5 hours
#SBATCH --mail-user=xuduo117@utexas.edu
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes

python shell_identifier_3_adaptive_lr.py  unet_newset_20190108_ep277_log_adaptive_lr             # run the MPI executable named a.out










